/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  dataStructureSidebar: [
    {
      type: 'category',
      label: '数据结构',
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-structure',
        },
      ],
    },
  ],
  algorithmsSystemsSidebar: [
    {
      type: 'category',
      label: '算法导论',
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction-to-algorithms',
        },
      ],
    },
  ],
  distributedSystemsSidebar: [
    {
      type: 'category',
      label: '分布式系统',
      items: [
        {
          type: 'autogenerated',
          dirName: 'distributed-systems',
        },
      ],
    },
  ],
  ddiaSidebar: [
    {
      type: 'category',
      label: '设计数据密集型应用',
      items: [
        {
          type: 'autogenerated',
          dirName: 'designing-data-intensive-application',
        },
      ],
    },
  ],
  codesSidebar: [
    {
      type: 'category',
      label: 'codes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codes',
        },
      ],
    },
  ],
};

module.exports = sidebars;
